export const MINT = 'mint'
export const APPROVE = 'approve'
export const REGISTER = 'register'
export const VEST = 'vest'
export const CONFIRM_VEST_INCREASE = 'confirm_vest_increase'
export const DEPOSIT = 'deposit'
